name: legendary_inventory
version: '1.0.0'
main: www.legendarycommunity.com.br.legendary_inventory.Legendary_inventory
api-version: '1.21'
authors: [ Thaynison ]
description: Plugin Legendary Community
website: http://www.legendarycommunity.com.br
